import { useMemo, useState } from "react";
import DashboardLayout from "../../layouts/DashboardLayout";

import {
  Box,
  Typography,
  Paper,
  Button,
  IconButton,
  TextField,
  MenuItem,
  Chip,
  Divider,
  LinearProgress,
  Tooltip,
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  Snackbar,
  Alert,
} from "@mui/material";

import DownloadRoundedIcon from "@mui/icons-material/DownloadRounded";
import PictureAsPdfRoundedIcon from "@mui/icons-material/PictureAsPdfRounded";
import AssessmentRoundedIcon from "@mui/icons-material/AssessmentRounded";
import TrendingUpRoundedIcon from "@mui/icons-material/TrendingUpRounded";
import TrendingDownRoundedIcon from "@mui/icons-material/TrendingDownRounded";
import PeopleAltRoundedIcon from "@mui/icons-material/PeopleAltRounded";
import ShieldRoundedIcon from "@mui/icons-material/ShieldRounded";
import WarningAmberRoundedIcon from "@mui/icons-material/WarningAmberRounded";
import SosRoundedIcon from "@mui/icons-material/SosRounded";
import LocationOnRoundedIcon from "@mui/icons-material/LocationOnRounded";
import RefreshRoundedIcon from "@mui/icons-material/RefreshRounded";
import CalendarMonthRoundedIcon from "@mui/icons-material/CalendarMonthRounded";
import SearchRoundedIcon from "@mui/icons-material/SearchRounded";
import VisibilityRoundedIcon from "@mui/icons-material/VisibilityRounded";
import CloseRoundedIcon from "@mui/icons-material/CloseRounded";
import AutoAwesomeRoundedIcon from "@mui/icons-material/AutoAwesomeRounded";
import MoreHorizRoundedIcon from "@mui/icons-material/MoreHorizRounded";

const reports = [
  {
    id: "RPT-1024",
    title: "Daily Tourist Safety Report",
    type: "Safety",
    date: "09 Aug 2026",
    period: "Today",
    status: "Ready",
    score: 94,
    incidents: 4,
    tourists: 273,
  },
  {
    id: "RPT-1023",
    title: "GeoFence Activity Analysis",
    type: "GeoFence",
    date: "08 Aug 2026",
    period: "Yesterday",
    status: "Ready",
    score: 91,
    incidents: 7,
    tourists: 318,
  },
  {
    id: "RPT-1022",
    title: "SOS Response Performance",
    type: "Emergency",
    date: "07 Aug 2026",
    period: "Last 7 days",
    status: "Ready",
    score: 88,
    incidents: 11,
    tourists: 421,
  },
  {
    id: "RPT-1021",
    title: "Tourist Movement Overview",
    type: "Tourist",
    date: "05 Aug 2026",
    period: "Last 30 days",
    status: "Ready",
    score: 96,
    incidents: 19,
    tourists: 1268,
  },
];

const activity = [
  { time: "10:42 AM", text: "Daily safety report generated", color: "#38BDF8" },
  { time: "09:18 AM", text: "High-risk zone analysis completed", color: "#F59E0B" },
  { time: "08:55 AM", text: "SOS response metrics synchronized", color: "#10B981" },
  { time: "Yesterday", text: "Monthly tourist report exported", color: "#818CF8" },
];

const Report = () => {
  const [dateRange, setDateRange] = useState("7");
  const [type, setType] = useState("All");
  const [search, setSearch] = useState("");
  const [preview, setPreview] = useState(null);
  const [toast, setToast] = useState(false);
  const [generating, setGenerating] = useState(false);

  const filteredReports = useMemo(() => {
    return reports.filter((report) => {
      const matchesType = type === "All" || report.type === type;
      const matchesSearch =
        `${report.title} ${report.id} ${report.type}`
          .toLowerCase()
          .includes(search.toLowerCase());

      return matchesType && matchesSearch;
    });
  }, [type, search]);

  const generateReport = () => {
    setGenerating(true);

    setTimeout(() => {
      setGenerating(false);
      setToast(true);
    }, 900);
  };

  const downloadReport = (report) => {
    const content = [
      "SAFETOUR AI — TOURIST SAFETY REPORT",
      "-----------------------------------",
      `Report ID: ${report.id}`,
      `Report: ${report.title}`,
      `Type: ${report.type}`,
      `Date: ${report.date}`,
      `Safety Score: ${report.score}%`,
      `Incidents: ${report.incidents}`,
      `Tourists Monitored: ${report.tourists}`,
      "",
      "Generated by SafeTour AI Monitoring System",
    ].join("\n");

    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const anchor = document.createElement("a");
    anchor.href = url;
    anchor.download = `${report.id}.txt`;
    anchor.click();
    URL.revokeObjectURL(url);
  };

  return (
    <DashboardLayout>
      <Box
        sx={{
          minHeight: "100vh",
          p: { xs: 1.5, md: 3 },
          color: "#EAF6FF",
          background: `
            radial-gradient(circle at 80% 5%, rgba(37,99,235,.18), transparent 28%),
            radial-gradient(circle at 5% 65%, rgba(14,165,233,.08), transparent 25%),
            linear-gradient(135deg,#06111F 0%,#081A2E 48%,#071525 100%)
          `,
          position: "relative",
          overflow: "hidden",
          "&::before": {
            content: '""',
            position: "absolute",
            width: 480,
            height: 480,
            borderRadius: "50%",
            background: "rgba(56,189,248,.05)",
            right: -220,
            top: 180,
            filter: "blur(80px)",
            pointerEvents: "none",
          },
        }}
      >
        <Box sx={{ maxWidth: 1700, mx: "auto", position: "relative", zIndex: 2 }}>
          {/* HEADER */}
          <Box
            sx={{
              display: "flex",
              justifyContent: "space-between",
              alignItems: "center",
              gap: 2,
              flexWrap: "wrap",
              mb: 3,
            }}
          >
            <Box sx={{ display: "flex", alignItems: "center", gap: 1.5 }}>
              <Box
                sx={{
                  width: 56,
                  height: 56,
                  borderRadius: "18px",
                  display: "flex",
                  alignItems: "center",
                  justifyContent: "center",
                  background: "linear-gradient(135deg,#2563EB,#06B6D4)",
                  boxShadow: "0 12px 35px rgba(37,99,235,.28)",
                  animation: "reportFloat 4s ease-in-out infinite",
                  "@keyframes reportFloat": {
                    "0%,100%": { transform: "translateY(0)" },
                    "50%": { transform: "translateY(-5px)" },
                  },
                }}
              >
                <AssessmentRoundedIcon sx={{ color: "#fff", fontSize: 30 }} />
              </Box>

              <Box>
                <Typography
                  sx={{
                    fontSize: { xs: 25, md: 32 },
                    fontWeight: 900,
                    letterSpacing: -1,
                    color: "#F8FAFC",
                  }}
                >
                  Safety Intelligence Reports
                </Typography>
                <Typography sx={{ color: "#7894AD", fontSize: 13, mt: 0.4 }}>
                  Analyze tourist activity, incidents, SOS events & zone performance
                </Typography>
              </Box>
            </Box>

            <Box sx={{ display: "flex", gap: 1 }}>
              <Chip
                label="● LIVE DATA"
                sx={{
                  height: 38,
                  borderRadius: "12px",
                  color: "#6EE7B7",
                  bgcolor: "rgba(16,185,129,.08)",
                  border: "1px solid rgba(16,185,129,.22)",
                  fontWeight: 800,
                  fontSize: 10,
                }}
              />

              <Button
                startIcon={
                  generating ? <RefreshRoundedIcon /> : <AssessmentRoundedIcon />
                }
                onClick={generateReport}
                disabled={generating}
                sx={{
                  height: 42,
                  px: 2,
                  borderRadius: "13px",
                  color: "#fff",
                  textTransform: "none",
                  fontWeight: 800,
                  background: "linear-gradient(135deg,#2563EB,#06B6D4)",
                  boxShadow: "0 10px 30px rgba(37,99,235,.25)",
                  "&:hover": {
                    background: "linear-gradient(135deg,#1D4ED8,#0891B2)",
                    transform: "translateY(-2px)",
                  },
                  transition: ".25s",
                }}
              >
                {generating ? "Generating..." : "Generate Report"}
              </Button>
            </Box>
          </Box>

          {/* KPI CARDS */}
          <Box
            sx={{
              display: "grid",
              gridTemplateColumns: { xs: "1fr 1fr", lg: "repeat(4,1fr)" },
              gap: 1.5,
              mb: 2,
            }}
          >
            <MetricCard
              icon={<PeopleAltRoundedIcon />}
              label="Tourists Monitored"
              value="2,384"
              change="+12.8%"
              detail="vs previous period"
              color="#38BDF8"
              up
            />
            <MetricCard
              icon={<ShieldRoundedIcon />}
              label="Safety Score"
              value="94.2%"
              change="+4.6%"
              detail="system-wide safety"
              color="#10B981"
              up
            />
            <MetricCard
              icon={<WarningAmberRoundedIcon />}
              label="Incidents"
              value="41"
              change="-18.4%"
              detail="vs previous period"
              color="#F59E0B"
            />
            <MetricCard
              icon={<SosRoundedIcon />}
              label="SOS Alerts"
              value="07"
              change="-31.2%"
              detail="response performance"
              color="#FB7185"
            />
          </Box>

          {/* ANALYTICS */}
          <Box
            sx={{
              display: "grid",
              gridTemplateColumns: { xs: "1fr", lg: "1.7fr 1fr" },
              gap: 1.5,
              mb: 2,
            }}
          >
            <Paper sx={panelSx}>
              <Box sx={{ display: "flex", justifyContent: "space-between", alignItems: "center", mb: 2 }}>
                <Box>
                  <Typography sx={sectionTitle}>Safety Performance</Typography>
                  <Typography sx={mutedText}>
                    System safety trend across monitored destinations
                  </Typography>
                </Box>

                <Chip
                  label="Last 7 days"
                  size="small"
                  sx={darkChip}
                />
              </Box>

              <Box sx={{ height: 205, display: "flex", alignItems: "flex-end", gap: { xs: 1, md: 2 }, px: 1 }}>
                {[72, 78, 74, 84, 81, 90, 94].map((value, index) => (
                  <Box
                    key={index}
                    sx={{
                      flex: 1,
                      height: "100%",
                      display: "flex",
                      flexDirection: "column",
                      justifyContent: "flex-end",
                      alignItems: "center",
                      gap: 0.8,
                    }}
                  >
                    <Typography sx={{ color: "#8DB5D2", fontSize: 9 }}>
                      {value}%
                    </Typography>
                    <Box
                      sx={{
                        width: "100%",
                        maxWidth: 48,
                        height: `${value * 1.55}px`,
                        maxHeight: 155,
                        borderRadius: "10px 10px 4px 4px",
                        background:
                          index === 6
                            ? "linear-gradient(180deg,#38BDF8,#2563EB)"
                            : "linear-gradient(180deg,#1E5B83,#123A5B)",
                        boxShadow:
                          index === 6
                            ? "0 0 25px rgba(56,189,248,.22)"
                            : "none",
                        transition: ".35s",
                        "&:hover": {
                          transform: "translateY(-5px)",
                          filter: "brightness(1.25)",
                        },
                      }}
                    />
                    <Typography sx={{ color: "#5E7892", fontSize: 8 }}>
                      {["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Today"][index]}
                    </Typography>
                  </Box>
                ))}
              </Box>
            </Paper>

            <Paper sx={panelSx}>
              <Box sx={{ display: "flex", alignItems: "center", gap: 1 }}>
                <Box sx={iconBox("#818CF8")}>
                  <AutoAwesomeRoundedIcon />
                </Box>
                <Box>
                  <Typography sx={sectionTitle}>AI Safety Insight</Typography>
                  <Typography sx={mutedText}>Automated analysis</Typography>
                </Box>
              </Box>

              <Box
                sx={{
                  mt: 2,
                  p: 1.7,
                  borderRadius: "15px",
                  bgcolor: "rgba(99,102,241,.08)",
                  border: "1px solid rgba(129,140,248,.15)",
                }}
              >
                <Typography sx={{ color: "#C7D2FE", fontSize: 12, lineHeight: 1.7 }}>
                  Tourist safety improved{" "}
                  <strong>4.6%</strong> this period. The strongest
                  performance is currently observed in active monitored
                  zones.
                </Typography>
              </Box>

              <Box sx={{ mt: 2 }}>
                <InsightRow label="Zone coverage" value="91%" color="#38BDF8" />
                <InsightRow label="SOS response" value="96%" color="#10B981" />
                <InsightRow label="Incident resolution" value="89%" color="#818CF8" />
              </Box>
            </Paper>
          </Box>

          {/* FILTER + REPORT LIST */}
          <Paper sx={{ ...panelSx, p: 0, overflow: "hidden" }}>
            <Box
              sx={{
                p: 2,
                display: "flex",
                justifyContent: "space-between",
                alignItems: "center",
                gap: 1.5,
                flexWrap: "wrap",
                borderBottom: "1px solid rgba(56,189,248,.09)",
              }}
            >
              <Box>
                <Typography sx={sectionTitle}>Generated Reports</Typography>
                <Typography sx={mutedText}>
                  Review and export operational reports
                </Typography>
              </Box>

              <Box sx={{ display: "flex", gap: 1, flexWrap: "wrap" }}>
                <TextField
                  size="small"
                  placeholder="Search reports..."
                  value={search}
                  onChange={(e) => setSearch(e.target.value)}
                  InputProps={{
                    startAdornment: (
                      <SearchRoundedIcon sx={{ mr: 1, color: "#4F7896" }} />
                    ),
                  }}
                  sx={fieldSx}
                />

                <TextField
                  select
                  size="small"
                  value={type}
                  onChange={(e) => setType(e.target.value)}
                  sx={{ ...fieldSx, width: 130 }}
                >
                  <MenuItem value="All">All Types</MenuItem>
                  <MenuItem value="Safety">Safety</MenuItem>
                  <MenuItem value="GeoFence">GeoFence</MenuItem>
                  <MenuItem value="Emergency">Emergency</MenuItem>
                  <MenuItem value="Tourist">Tourist</MenuItem>
                </TextField>

                <TextField
                  select
                  size="small"
                  value={dateRange}
                  onChange={(e) => setDateRange(e.target.value)}
                  sx={{ ...fieldSx, width: 135 }}
                >
                  <MenuItem value="1">Today</MenuItem>
                  <MenuItem value="7">Last 7 Days</MenuItem>
                  <MenuItem value="30">Last 30 Days</MenuItem>
                </TextField>
              </Box>
            </Box>

            {/* REPORT CARDS */}
            <Box sx={{ p: 2, display: "grid", gap: 1 }}>
              {filteredReports.map((report) => (
                <Box
                  key={report.id}
                  sx={{
                    display: "grid",
                    gridTemplateColumns: {
                      xs: "1fr",
                      md: "2.1fr 1fr 1fr 1fr auto",
                    },
                    gap: 2,
                    alignItems: "center",
                    p: 1.5,
                    borderRadius: "15px",
                    bgcolor: "rgba(255,255,255,.025)",
                    border: "1px solid rgba(148,163,184,.08)",
                    transition: ".25s",
                    "&:hover": {
                      bgcolor: "rgba(56,189,248,.045)",
                      borderColor: "rgba(56,189,248,.18)",
                      transform: "translateX(3px)",
                    },
                  }}
                >
                  <Box sx={{ display: "flex", alignItems: "center", gap: 1.3 }}>
                    <Box sx={iconBox("#38BDF8")}>
                      <AssessmentRoundedIcon />
                    </Box>

                    <Box>
                      <Typography sx={{ color: "#EAF6FF", fontSize: 12, fontWeight: 800 }}>
                        {report.title}
                      </Typography>
                      <Typography sx={{ color: "#607D97", fontSize: 9, mt: 0.3 }}>
                        {report.id} • {report.date}
                      </Typography>
                    </Box>
                  </Box>

                  <Box>
                    <Typography sx={labelText}>TYPE</Typography>
                    <Chip label={report.type} size="small" sx={darkChip} />
                  </Box>

                  <Box>
                    <Typography sx={labelText}>SAFETY SCORE</Typography>
                    <Box sx={{ display: "flex", alignItems: "center", gap: 1 }}>
                      <Typography sx={{ color: "#F8FAFC", fontSize: 14, fontWeight: 900 }}>
                        {report.score}%
                      </Typography>
                      <Box sx={{ width: 65 }}>
                        <LinearProgress
                          variant="determinate"
                          value={report.score}
                          sx={{
                            height: 5,
                            borderRadius: 5,
                            bgcolor: "rgba(255,255,255,.06)",
                            "& .MuiLinearProgress-bar": {
                              borderRadius: 5,
                              background: "linear-gradient(90deg,#10B981,#38BDF8)",
                            },
                          }}
                        />
                      </Box>
                    </Box>
                  </Box>

                  <Box>
                    <Typography sx={labelText}>ACTIVITY</Typography>
                    <Typography sx={{ color: "#8DA8BE", fontSize: 9 }}>
                      {report.incidents} incidents • {report.tourists} tourists
                    </Typography>
                  </Box>

                  <Box sx={{ display: "flex", gap: 0.5, justifyContent: { md: "flex-end" } }}>
                    <Tooltip title="Preview report">
                      <IconButton
                        size="small"
                        onClick={() => setPreview(report)}
                        sx={actionButton("#38BDF8")}
                      >
                        <VisibilityRoundedIcon fontSize="small" />
                      </IconButton>
                    </Tooltip>

                    <Tooltip title="Download">
                      <IconButton
                        size="small"
                        onClick={() => downloadReport(report)}
                        sx={actionButton("#10B981")}
                      >
                        <DownloadRoundedIcon fontSize="small" />
                      </IconButton>
                    </Tooltip>

                    <Tooltip title="More">
                      <IconButton size="small" sx={actionButton("#94A3B8")}>
                        <MoreHorizRoundedIcon fontSize="small" />
                      </IconButton>
                    </Tooltip>
                  </Box>
                </Box>
              ))}

              {filteredReports.length === 0 && (
                <Box sx={{ textAlign: "center", py: 7 }}>
                  <AssessmentRoundedIcon sx={{ color: "#34536D", fontSize: 45 }} />
                  <Typography sx={{ color: "#7894AD", mt: 1 }}>
                    No reports found
                  </Typography>
                </Box>
              )}
            </Box>
          </Paper>

          {/* BOTTOM ROW */}
          <Box
            sx={{
              display: "grid",
              gridTemplateColumns: { xs: "1fr", md: "1fr 1fr" },
              gap: 1.5,
              mt: 2,
            }}
          >
            <Paper sx={panelSx}>
              <Box sx={{ display: "flex", alignItems: "center", gap: 1, mb: 2 }}>
                <Box sx={iconBox("#F59E0B")}>
                  <CalendarMonthRoundedIcon />
                </Box>
                <Box>
                  <Typography sx={sectionTitle}>Report Schedule</Typography>
                  <Typography sx={mutedText}>Automated reporting pipeline</Typography>
                </Box>
              </Box>

              <ScheduleRow title="Daily Safety Summary" time="Every day • 11:00 PM" active />
              <ScheduleRow title="Weekly GeoFence Analysis" time="Every Monday • 08:00 AM" active />
              <ScheduleRow title="Monthly Operations Report" time="1st day of month" active />
            </Paper>

            <Paper sx={panelSx}>
              <Typography sx={sectionTitle}>Recent Activity</Typography>
              <Typography sx={{ ...mutedText, mb: 1.5 }}>
                Latest report operations
              </Typography>

              {activity.map((item) => (
                <Box
                  key={item.time + item.text}
                  sx={{
                    display: "flex",
                    alignItems: "center",
                    gap: 1.2,
                    py: 1,
                    borderBottom: "1px solid rgba(148,163,184,.06)",
                  }}
                >
                  <Box
                    sx={{
                      width: 8,
                      height: 8,
                      borderRadius: "50%",
                      bgcolor: item.color,
                      boxShadow: `0 0 10px ${item.color}88`,
                    }}
                  />
                  <Typography sx={{ color: "#9AB1C6", fontSize: 10, flex: 1 }}>
                    {item.text}
                  </Typography>
                  <Typography sx={{ color: "#526F89", fontSize: 8 }}>
                    {item.time}
                  </Typography>
                </Box>
              ))}
            </Paper>
          </Box>
        </Box>

        {/* PREVIEW DIALOG */}
        <Dialog
          open={Boolean(preview)}
          onClose={() => setPreview(null)}
          fullWidth
          maxWidth="sm"
          PaperProps={{
            sx: {
              bgcolor: "#0B2035",
              color: "#EAF6FF",
              border: "1px solid rgba(56,189,248,.16)",
              borderRadius: "20px",
              backgroundImage: "none",
              boxShadow: "0 30px 80px rgba(0,0,0,.55)",
            },
          }}
        >
          {preview && (
            <>
              <DialogTitle sx={{ fontWeight: 900 }}>
                <Box sx={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
                  Report Preview
                  <IconButton onClick={() => setPreview(null)} sx={{ color: "#7894AD" }}>
                    <CloseRoundedIcon />
                  </IconButton>
                </Box>
              </DialogTitle>

              <DialogContent>
                <Box sx={{ p: 2, borderRadius: "15px", bgcolor: "rgba(255,255,255,.035)", mb: 2 }}>
                  <Typography sx={{ color: "#38BDF8", fontSize: 9, fontWeight: 800 }}>
                    {preview.id}
                  </Typography>
                  <Typography sx={{ color: "#F8FAFC", fontSize: 20, fontWeight: 900, mt: 0.5 }}>
                    {preview.title}
                  </Typography>
                  <Typography sx={{ color: "#6F8BA7", fontSize: 10, mt: 0.5 }}>
                    Generated {preview.date}
                  </Typography>
                </Box>

                <Box sx={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 1 }}>
                  <PreviewStat label="Safety Score" value={`${preview.score}%`} />
                  <PreviewStat label="Incidents" value={preview.incidents} />
                  <PreviewStat label="Tourists" value={preview.tourists} />
                  <PreviewStat label="Status" value={preview.status} />
                </Box>

                <Box sx={{ mt: 2 }}>
                  <Typography sx={{ color: "#7894AD", fontSize: 10, mb: 1 }}>
                    REPORT SUMMARY
                  </Typography>
                  <Typography sx={{ color: "#AFC4D6", fontSize: 11, lineHeight: 1.8 }}>
                    This operational report summarizes monitored tourist activity,
                    safety performance and incident data for the selected reporting
                    period. All displayed metrics are ready for export.
                  </Typography>
                </Box>
              </DialogContent>

              <DialogActions sx={{ p: 2 }}>
                <Button
                  onClick={() => downloadReport(preview)}
                  startIcon={<DownloadRoundedIcon />}
                  sx={{
                    color: "#fff",
                    textTransform: "none",
                    fontWeight: 800,
                    bgcolor: "#2563EB",
                    borderRadius: "10px",
                    px: 2,
                    "&:hover": { bgcolor: "#1D4ED8" },
                  }}
                >
                  Export Report
                </Button>
              </DialogActions>
            </>
          )}
        </Dialog>

        <Snackbar
          open={toast}
          autoHideDuration={2500}
          onClose={() => setToast(false)}
          anchorOrigin={{ vertical: "bottom", horizontal: "right" }}
        >
          <Alert severity="success" onClose={() => setToast(false)}>
            Report generated successfully.
          </Alert>
        </Snackbar>
      </Box>
    </DashboardLayout>
  );
};

const panelSx = {
  p: 2,
  borderRadius: "20px",
  background: "linear-gradient(145deg,rgba(14,35,57,.96),rgba(7,22,38,.98))",
  border: "1px solid rgba(56,189,248,.11)",
  boxShadow: "0 20px 55px rgba(0,0,0,.28)",
  backdropFilter: "blur(18px)",
  color: "#EAF6FF",
};

const sectionTitle = {
  color: "#EAF6FF",
  fontSize: 14,
  fontWeight: 850,
};

const mutedText = {
  color: "#66829D",
  fontSize: 9,
  mt: 0.35,
};

const labelText = {
  color: "#55728B",
  fontSize: 7,
  fontWeight: 850,
  letterSpacing: 1,
  mb: 0.5,
};

const fieldSx = {
  width: 210,
  "& .MuiOutlinedInput-root": {
    height: 38,
    borderRadius: "11px",
    color: "#DCEEFF",
    bgcolor: "rgba(255,255,255,.035)",
    "& fieldset": {
      borderColor: "rgba(148,163,184,.14)",
    },
    "&:hover fieldset": {
      borderColor: "rgba(56,189,248,.28)",
    },
    "&.Mui-focused fieldset": {
      borderColor: "#38BDF8",
    },
  },
  "& input": {
    fontSize: 10,
    color: "#DCEEFF",
    "&::placeholder": {
      color: "#607B95",
      opacity: 1,
    },
  },
};

const darkChip = {
  height: 23,
  color: "#8CC9EA",
  bgcolor: "rgba(56,189,248,.08)",
  border: "1px solid rgba(56,189,248,.13)",
  fontSize: 8,
  fontWeight: 800,
};

const iconBox = (color) => ({
  width: 38,
  height: 38,
  borderRadius: "12px",
  display: "flex",
  alignItems: "center",
  justifyContent: "center",
  color,
  bgcolor: `${color}12`,
  border: `1px solid ${color}22`,
  boxShadow: `0 0 22px ${color}08`,
});

const actionButton = (color) => ({
  color,
  bgcolor: `${color}09`,
  border: `1px solid ${color}18`,
  "&:hover": {
    bgcolor: `${color}18`,
    transform: "translateY(-2px)",
  },
  transition: ".2s",
});

const MetricCard = ({ icon, label, value, change, detail, color, up }) => (
  <Paper
    sx={{
      ...panelSx,
      p: 1.8,
      transition: ".3s",
      "&:hover": {
        transform: "translateY(-4px)",
        borderColor: `${color}35`,
        boxShadow: `0 22px 55px ${color}10`,
      },
    }}
  >
    <Box sx={{ display: "flex", justifyContent: "space-between" }}>
      <Box>
        <Typography sx={{ color: "#65819B", fontSize: 8, fontWeight: 850, textTransform: "uppercase", letterSpacing: 1 }}>
          {label}
        </Typography>
        <Typography sx={{ color: "#F8FAFC", fontSize: 27, fontWeight: 900, mt: 0.7 }}>
          {value}
        </Typography>
        <Box sx={{ display: "flex", alignItems: "center", gap: 0.4, mt: 0.4 }}>
          {up ? (
            <TrendingUpRoundedIcon sx={{ fontSize: 14, color: "#34D399" }} />
          ) : (
            <TrendingDownRoundedIcon sx={{ fontSize: 14, color: "#34D399" }} />
          )}
          <Typography sx={{ color: "#34D399", fontSize: 9, fontWeight: 800 }}>
            {change}
          </Typography>
          <Typography sx={{ color: "#526F89", fontSize: 8 }}>
            {detail}
          </Typography>
        </Box>
      </Box>

      <Box sx={iconBox(color)}>{icon}</Box>
    </Box>
  </Paper>
);

const InsightRow = ({ label, value, color }) => (
  <Box sx={{ mb: 1.2 }}>
    <Box sx={{ display: "flex", justifyContent: "space-between", mb: 0.5 }}>
      <Typography sx={{ color: "#7894AD", fontSize: 9 }}>{label}</Typography>
      <Typography sx={{ color, fontSize: 9, fontWeight: 800 }}>{value}</Typography>
    </Box>
    <LinearProgress
      variant="determinate"
      value={parseInt(value)}
      sx={{
        height: 5,
        borderRadius: 5,
        bgcolor: "rgba(255,255,255,.05)",
        "& .MuiLinearProgress-bar": {
          borderRadius: 5,
          background: `linear-gradient(90deg,${color},#38BDF8)`,
        },
      }}
    />
  </Box>
);

const ScheduleRow = ({ title, time, active }) => (
  <Box
    sx={{
      display: "flex",
      alignItems: "center",
      gap: 1.2,
      p: 1,
      mb: 0.8,
      borderRadius: "11px",
      bgcolor: "rgba(255,255,255,.025)",
      border: "1px solid rgba(148,163,184,.07)",
    }}
  >
    <CalendarMonthRoundedIcon sx={{ color: "#38BDF8", fontSize: 18 }} />
    <Box sx={{ flex: 1 }}>
      <Typography sx={{ color: "#AFC4D6", fontSize: 10, fontWeight: 700 }}>
        {title}
      </Typography>
      <Typography sx={{ color: "#55728B", fontSize: 8, mt: 0.3 }}>
        {time}
      </Typography>
    </Box>
    <Chip
      label={active ? "ACTIVE" : "OFF"}
      size="small"
      sx={{
        height: 20,
        color: active ? "#6EE7B7" : "#7894AD",
        bgcolor: active ? "rgba(16,185,129,.08)" : "rgba(255,255,255,.04)",
        fontSize: 7,
        fontWeight: 800,
      }}
    />
  </Box>
);

const PreviewStat = ({ label, value }) => (
  <Box
    sx={{
      p: 1.4,
      borderRadius: "12px",
      bgcolor: "rgba(255,255,255,.035)",
      border: "1px solid rgba(148,163,184,.07)",
    }}
  >
    <Typography sx={{ color: "#607D97", fontSize: 8 }}>{label}</Typography>
    <Typography sx={{ color: "#F8FAFC", fontSize: 17, fontWeight: 900, mt: 0.4 }}>
      {value}
    </Typography>
  </Box>
);

export default Report;